Website [Patch 1]
BuildForSDG/team-134 pull request #33
Opened 2020-05-26 08:08 UTC by IanGeorgeGitau

Patch 1
---------------------------------------------------------------------------

- Contains Web Page Pages: (Home, About, Sign Up & Contact Us).

- Contains Web Page Styles (In CSS) For All Four Pages.

- Contains Web Page Images For Team Members. (Holds 3 images for Makavura, Eric Kioko & Ian George. Still requires 3 decent looking/semi-professional photos from Allan Mwirigi, John Macharia, and Peter Kiptanui).

2020-05-26 08:51 UTC, AllanMwirigi requested changes
Looks good.
Though codacy checks are failing.
Check that you've set up es-lint properly on your text editor. 
If it's VS Code, you can hover on any line with an error and select 'Fix all auto-fixable problems' from the context menu. This should resolve most of the issues automatically

2020-05-26 08:58 UTC, IanGeorgeGitau commented
Thank You, Allan I'm On It.

2020-05-26 09:13 UTC, IanGeorgeGitau commented
All Checks Passed. Please Proceed To Review

2020-05-26 09:29 UTC, AllanMwirigi approved these changes

2020-05-29 08:45 UTC, collengine approved these changes

2020-06-01 05:58 UTC, Makavura approved these changes

2020-06-01 05:58 UTC, merged